### ISSUE TITLE
Transferring trebuchet to another account

### ISSUE THREAD

**Issue by ghost** [revarbat/trebuchet#4]
In the comments for
https://github.com/revarbat/trebuchet/pull/3
there was some discussion of changing the ownership of the trebuchet repository from @revarbat to someone else.
I suggested @fuzzball-muck as a possibility for an account to transfer to.

The steps to just transfer the trebuchet repository here between two GitHub accounts are quite easy:
https://help.github.com/en/articles/transferring-a-repository
**So all that needs to be done is decide where to transfer it to, and then for @revarbat to do it.**
:D

Having this in its own GH issue makes it easier to talk about, in a more visible and organised spot.

(pinging @wyld-sw so he sees this)

I also mentioned an **entirely optional** license change.  I want to emphasise that's **optional** and if it's a blocker, doesn't need to happen!  I worry I didn't make that clear earlier. >w>
My bad if I was unclear.  It was just a potential little bonus to make things easier for the new repo owners and new devs.

**Comment by ghost** [comment]
Optionally, some stuff could also be done about the sourceforge site and other things, but the stuff in the OP to this issue is most relevant to here.

**Comment by revarbat** [comment]
I don't mind a license change, so long as it's one of MIT, BSD (2 or 3 clause), GPL, or Apache license.  In general, I prefer MIT or BSD 2 clause.

**Comment by revarbat** [comment]
I do appear to still have the original files in the belfry.com/fuzzball directory.

**Comment by revarbat** [comment]
ATTN: @wyld-sw

Attempted to transfer repo to @fuzzball-muck, and I got the following error:
> You don’t have the permission to create repositories on fuzzball-muck

**Comment by ghost** [comment]
> I don't mind a license change, so long as it's one of MIT, BSD (2 or 3 clause), GPL, or Apache license. In general, I prefer MIT or BSD 2 clause.

Yeah!  Permission for your Trebuchet code to be MIT-licensed would be great.  Then we'd just have to find a couple other people and we'd (hopefully) be set.
(entirely unrelatedly, we're also looking into, as a long-term goal, seeing if we can re-license the GPL'd code in fuzzball to MIT.  Permission for that too, for your GPL'd code in fuzzball, would be great too :D  The reason we're doing it in fuzzball though is because the old license and GPL are very likely incompatible, and that's a legal issue.  for trebuchet it would merely be for convenience though, rather than that important reason)
But indeed, it isn't the biggest issue here, but it is nice. :heart: 

> I do appear to still have the original files in the belfry.com/fuzzball directory.

Nice :D
Think you could put the whole folder into a .tar.gz somewhere?

**Comment by wyld-sw** [comment]
> Attempted to transfer repo to @fuzzball-muck, and I got the following error ...

I just invited you to the fuzzball-muck organization, and enabled repository creation. Let me know if that doesn't do it.

> Think you could put the whole folder into a .tar.gz somewhere?

Feel free to send it to wyld@fuzzball.org if it's email-sized. Whatever works though!

**Comment by revarbat** [comment]
Repo transferred.

The belfry.com/fuzzball directories can be downloaded as http://belfry.com/fbdirs.tar.gz

**Comment by ghost** [comment]
> Repo transferred.
> 
> The belfry.com/fuzzball directories can be downloaded as http://belfry.com/fbdirs.tar.gz

Thanks :D

**Comment by ghost** [comment]
I notice the /pics/ directory is missing, hence missing images, when the image links use relative directories.  Amusingly enough, pages that use links with absolute URL links to belfry.com, those images show up just fine, as the /pics/ directory also still exists on belfry.com

**Comment by ghost** [comment]
I don't think any of the images in the /pics/ folder (there are some images included in the tarball) are important, to my memory, other than being very cute art of feeps, so, I'm fine with @wyld-sw closing this issue if he wishes.
If we discover needing images later, I'll contact you, @revarbat :D  (or we could get them now, but either way)

**Comment by ghost** [comment]
And of course there's still sourceforge, but, hmm.  This can stay open or closed.
(sorry for doing like four comments in a row :B )
